#!/bin/sh -e
# live-build configuration script
# see 'man lb config'

lb config noauto \
--clean \
--ignore-system-defaults \
--apt-recommends true \
--apt-indices false \
--mode debian \
--distribution trixie \
--architectures amd64 \
--archive-areas 'main contrib non-free non-free-firmware' \
--updates true \
--security true \
--backports true \
--source false \
--firmware-chroot false \
--firmware-binary false \
--binary-images iso-hybrid \
--debian-installer live \
--debian-installer-distribution trixie \
--debconf-frontend noninteractive \
--debootstrap-options "--variant=minbase --include=apt-transport-https,ca-certificates,openssl" \
--linux-packages "linux-image linux-headers" \
--initramfs live-boot \
--bootappend-live "boot=live config splash components user-setup sudo hostname=trixie-live locales=en_US.UTF-8,de_DE.UTF-8,C.UTF-8 keyboard-layouts=de " \
--iso-publisher wandsas \
--iso-volume "debian-live" \
"${@}"
