#!/bin/sh -e
# live-build configuration script
# see 'man lb config'

lb config noauto \
--clean \
--ignore-system-defaults \
--apt-recommends false \
--mode debian \
--distribution trixie \
--architectures amd64 \
--archive-areas 'main contrib non-free non-free-firmware' \
--updates true \
--security true \
--backports true \
--source false \
--binary-images iso-hybrid \
--debian-installer live \
--debian-installer-distribution trixie \
--debconf-frontend noninteractive \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--linux-packages "linux-image linux-headers" \
--initramfs live-boot \
--bootappend-live "boot=live config splash components user-setup sudo " \
--iso-publisher wandsas \
--iso-volume "debian-live" \
"${@}"
